openapi: 3.0.3
info:
  title: Hamburg Rails API
  version: 1.0.0
paths:
  /graph:
    get:
      summary: Get current edge list and node count
      responses:
        '200':
          description: Graph data
  /shortest:
    get:
      summary: Compute shortest path between two nodes
      parameters:
        - in: query
          name: from
          required: true
          schema: { type: string }
        - in: query
          name: to
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Shortest path result
  /trips:
    get:
      summary: Count trips by number of stops
      parameters:
        - in: query
          name: from
          required: true
          schema: { type: string }
        - in: query
          name: to
          required: true
          schema: { type: string }
        - in: query
          name: minStops
          required: true
          schema: { type: integer }
        - in: query
          name: maxStops
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Trip count result